### ISSUE TITLE
The plug-in stops working if you enter the note from a Joplin link in Another Note

### ISSUE THREAD

**Issue by hplphotos** [CalebJohn/joplin-math-mode#1]
CalebJohn,

I've done a bit of testing on your great new Math plugin. It works as expected, except for one issue. I embedded a link to the note ("first note") with the fenced math code inside a second note. In "preview" mode, I clicked on the link in the second note to take me back to the first note. Back in the first note, I noticed that the plugin stopped working. All I saw inside the fenced code was what I originally typed, not the calculated results. Entering the note via a link from another note appears not to tell the plugin to start. 

To get around this, I typed some random text inside the note with the fenced math code and then erased it character by character. When I erased the last character of random text, the math plugin worded again and the calculations were done correctly.

I hope I explained this clearly enough. I noticed on your roadmap, under "Maybe", that you are considering having the calculation results being displayed in "Preview" mode. I think that would be very useful.

Thanks again for working on this. I expect to use this plugin in many notes that need calculations, such as notes on investments.

**Comment by CalebJohn** [comment]
Thanks for reporting this @hplphotos. 

Indeed there was enough information to figure out the issue. But just to confirm, this only happened when the first note only contained a single line, correct? That's the issue I fixed, so if you can still reproduce this issue on v0.1.1 please re-open this issue and let me know!
