### ISSUE TITLE
Bug: sum starting < 0

### ISSUE THREAD

**Issue by panathos** [CalebJohn/joplin-math-mode#10]
Finding another bug.

This is no good, expected result: 190.53
![image](https://user-images.githubusercontent.com/10244779/111007941-46b92480-8390-11eb-9906-b7de7ee7a258.png)

Insert leading 0, same problem:
![image](https://user-images.githubusercontent.com/10244779/111007994-69e3d400-8390-11eb-8f71-f90374a867e9.png)

Inserting any another number fix answer:
![image](https://user-images.githubusercontent.com/10244779/111008047-8b44c000-8390-11eb-9349-cf8bafb8ffd7.png)

Thank you for your effort.

**Comment by CalebJohn** [comment]
Thanks for finding this, it seems that if the first element in a block is the explicit total subtraction, it will be treated as a positive, not negative.

For now you can just replace `-= 24.80` with `-24.80`. But I will push an update later today, so it won't be a problem for long.

**Comment by CalebJohn** [comment]
@panathos This is fixed now. I've pushed the fix up as v0.4.2. I'm note sure how often the plugins actually get pulled by the Joplin plugin system, but the fix should be available in the next couple of days!

Thanks again. Please keep the reports coming!

**Comment by panathos** [comment]
Thank you @CalebJohn 👍
