### ISSUE TITLE
fetch currency data

### ISSUE THREAD

**Issue by tessus** [CalebJohn/joplin-math-mode#15]
I've been wondering, if there should be an option to disable fetching of currency data.

**Comment by CalebJohn** [comment]
I hadn't considered it, but there definitely should be. I'll get on it.

**Comment by Rolograaf** [comment]
> I've been wondering, if there should be an option to disable fetching of currency data.

you mean like this?

![math_€](https://user-images.githubusercontent.com/6130902/119226617-59777480-bb0a-11eb-8be3-fc1c77b1e611.png)

because I use price calculations all the time in Joplin notes and it would be nice if I could put away my calculator...

**Comment by CalebJohn** [comment]
Hi @Rolograaf

Currently this plugin doesn't support using a prefix currency like you've done. The way the currency support works is that you need to include the currency after the number.

For example
```
100 CAD
127.65 CAD in JPY
```
I think it should be possible to support actual currency symbols in the future. But its not implemented currently.

**Comment by tessus** [comment]
@CalebJohn I've just noticed that you might have misunderstood my original question. 

There is now an option: `Enable currency conversions`. But unchecking it turns it off completely. It also means that all my current notes with conversion formulas will throw an error (`Undefined symbol ...`). 
I rather meant to be able to turn off fetching of the conversion data every day. (So that there are no outgoing requests.)

Or does this make no sense? Maybe I'm just overthinking it.

**Comment by CalebJohn** [comment]
I can add an option to adjust the fetch frequency, or maybe a manual fetch button? 
Another option would be to only update if it's been a day **and** a note with conversions are opened?

What's your use case? Are you trying to pin the conversion to a specific date?

**Comment by tessus** [comment]
For me personally it's not a big deal. I use LittleSnitch to control my outgoing connections. But having a plugin to initiate outgoing requests without the user's permission might be considered invasive.

My idea was to give the user to option to allow/disable these requests in the plugin settings. But as I said, maybe I'm overthinking it.

**Comment by CalebJohn** [comment]
The problem is that the currency data has to come from somewhere, so if currencies are enabled the plugin will fetch currency data on startup and continue fetching it once per day to ensure the currencies are up-to-date. If not, there's no way for the plugin to know what the conversion rates are.

I could add currency units without including conversions between them. So you could use math like `100 CAD/day` but not `100 CAD in USD`. Is that something you think would be useful?

**Comment by tessus** [comment]
Ok, I see. I would have just added a warning, if no currency data has been fetched and/or is older than X days.
Someone who disables the retrieval of new data should know that the data might not be accurate and thus stale.

But no worries. This was just an idea. The current option also disables outgoing requests, so it's fine. I don't think additional options are needed.
