### ISSUE TITLE
Rows intended when expressions not hidden

### ISSUE THREAD

**Issue by AndreasMartin72** [CalebJohn/joplin-math-mode#18]
Since upgrading to Joplin v2.3.5 I get the following output:

```math
t_1 = 12 h => t_1: 12 h
           t_2 = 40 h => t_2: 40 h
                      m = 11 => m: 11
                             (t_1/t_2)^(2/m) => 0.80.......
```

When disabling expressions (hide: expression), all looks fine.

**Comment by CalebJohn** [comment]
Thanks for the report @AndreasMartin72. This was a weird bug because I could not duplicate it on my development computer (which makes fixing it a pain). I was luckily able to duplicate this on my work machine, and have created a release that should fix it. Please give v0.5.3 a test and let me know.

**Comment by AndreasMartin72** [comment]
Where do I find the release for testing? (I searched in section "Releases" in this repository)

**Comment by AndreasMartin72** [comment]
Works fine again, thank you!
