### ISSUE TITLE
Doesn't work with the new editor

### ISSUE THREAD

**Issue by banan314** [CalebJohn/joplin-math-mode#28]
![image](https://github.com/user-attachments/assets/9505551c-edad-44a6-9607-d0526dd67306)

After switching off the legacy editor in Joplin 3.0.15 (it worked in 3.0.8, I didn't use the ones in between), math mode doesn't work anymore
![image](https://github.com/user-attachments/assets/29d8454c-667f-4bdd-997b-85978e31328f)

It still works with the legacy editor on 
![image](https://github.com/user-attachments/assets/1a73c012-2002-4ad8-9e48-1de313c1bf9f)

**Comment by CalebJohn** [comment]
Updating is a work in progress, you can track it here
https://github.com/CalebJohn/joplin-math-mode/pull/26
