### ISSUE TITLE
does not honor the fenced block

### ISSUE THREAD

**Issue by tessus** [CalebJohn/joplin-math-mode#5]
It seems that the codeblock with `math` is not even needed.

See:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/223439/106398311-2042b980-63e0-11eb-92be-ef058d49c056.png">

This can be a problem when it tries to evaluate stuff in normal notes.....

**Comment by CalebJohn** [comment]
The first line is expected, I call them "inline math", you can see more examples in the README. But the second is a something I hadn't thought of, I'll fix it soon.

I was always planning on having a setting to disable the inline math option, I'll look into that as well.

**Comment by tessus** [comment]
> The first line is expected, I call them "inline math"

Ah, ok. Interesting. Can come in handy. I just didn't know that this is possible without a math fenced block.
So it sems that this only works when the first charcer in a line is `=`. Cool.

> But the second is a something I hadn't thought of, I'll fix it soon.

Sounds good.

**Comment by CalebJohn** [comment]
Thanks again for the report @tessus, I've fixed this and I plan on pushing a new release soon.
