### ISSUE TITLE
use of random function

### ISSUE THREAD

**Issue by tomhull** [CalebJohn/joplin-math-mode#6]
Cool plugin, although trying to get a random number generator appears to be broken for me.

Using Joplin 1.7.11 and Math Mode v0.3.0

```
combinations(6, 3) // works fine
random([1]) // ok
random(1, 100)  // gives error:
```

`Unexpected type of argument in function random (expected: number or Array or Matrix or string or boolean, actual: BigNumber, index: 0)`

Expected behavior is a random number between 1 and 100 as per mathjs docs.

**Comment by CalebJohn** [comment]
Thanks for reporting this, this plugin uses mathjs's BigNumber by default. I hadn't realized how many functions this was broken for. I'll revert to regular numbers for the next point release. And leave BigNumbers as an option for those that want them.
