### ISSUE TITLE
Rendering to viewer

### ISSUE THREAD

**Issue by breisfeld** [CalebJohn/joplin-math-mode#8]
The math mode plugin is very useful!

I may be missing something obvious, but is there a way to have it render output to the viewer pane?

**Comment by CalebJohn** [comment]
Thanks! The only thing your missing is the [planned features list](https://github.com/CalebJohn/joplin-math-mode#todo).

I do consider it to be fairly low priority though, so it might be a few weeks or months before I get around to it.
