### ISSUE TITLE
Is plugin working?

### ISSUE THREAD

**Issue by panathos** [CalebJohn/joplin-math-mode#9]
Installed plugin, restarted Joplin, I see fenced code block with no calc.
What I'm missing?

Code block:
![image](https://user-images.githubusercontent.com/10244779/110858433-5c5c1a80-82ba-11eb-8a2f-800a9bfa6c27.png)

Render block
![image](https://user-images.githubusercontent.com/10244779/110858606-90cfd680-82ba-11eb-92d9-6ea2cda8747a.png)

Updated with your examples:

Code block
![image](https://user-images.githubusercontent.com/10244779/110858913-f3c16d80-82ba-11eb-8fb7-e928d47328dd.png)

Render block
![image](https://user-images.githubusercontent.com/10244779/110858966-0471e380-82bb-11eb-98a2-6ac72a234e71.png)

**Comment by CalebJohn** [comment]
Hi @panathos 

What version of Joplin are you using? The plugin requires version 1.7.x and above.

Another possible issue would be that perhaps Joplin didn't restart correctly? You can try closing Joplin with File -> Quit, in order to make sure it actual restarts.

**Comment by panathos** [comment]
```
Joplin 1.7.11 (prod, win32)

ID del Client: 327d0ca9136c4d2891cbcdfcd996c274
Sinc. versione: 2
Profilo versione: 34
Portachiavi supportato: Sì

Revisione: f560563d8 (master)
```
Joplin installed with [scoop.sh](https://scoop.sh/) in Windows 10 64 bit.

Now i tried to deleted plugin, File->Quit, reinstalled, restarted Joplin, but same situation: no calculus appeared.

I love this plugin, what else can do? Thank you for your effort.

**Comment by CalebJohn** [comment]
Have you been able to successfully install any other plugins?

**Comment by panathos** [comment]
Now trying `Markdown table calculations plugin`, is working.

![image](https://user-images.githubusercontent.com/10244779/110904840-dff12800-8309-11eb-8252-823d544d5e34.png)

**Comment by CalebJohn** [comment]
If you go under Tools -> Options, along there left bar there will be options for each section. Towards the bottom is the plugin specific options. Are the math mode plugin options there?

**Comment by panathos** [comment]
Yes, there is, along with options on the right.

![image](https://user-images.githubusercontent.com/10244779/110976616-66852400-8361-11eb-9537-82457e469023.png)

**Comment by CalebJohn** [comment]
I got it! I tried duplicating your first example and the results didn't show!
The parser the plugin uses apparently doesn't support commas, which was causing it to crash. It's supposed to show an error when that happens but it crashed hard.

You can just remove the commas for now and the results should show normally. I'm working on a fix and will push an update later.

**Comment by panathos** [comment]
Great, you got it! Deleting commas is OK. 

![image](https://user-images.githubusercontent.com/10244779/110985917-4fe4ca00-836d-11eb-99f3-f824ec4b091c.png)

But dots instead of commas causes strange result:

![image](https://user-images.githubusercontent.com/10244779/110986156-99cdb000-836d-11eb-9ec5-c7d9214f6b39.png)

Maybe italian locale causes problem with library?

**Comment by CalebJohn** [comment]
The behaviour now is due to your settings, just toggle this setting and the numbers will show normally
![image](https://user-images.githubusercontent.com/2179547/110987285-19d32600-832c-11eb-85b0-77ecae8463cd.png)

I might hide that option under advanced, because most people probably won't want it.

I think this issue is now solved, thanks for finding the bug and working with me to solve it. I hope you enjoy the plugin. Let me know if you have any more issues or comments.
